usage: |
  §a/<command> toggle bar§r - show TPS information in action bar
  §a/<command> toggle tab§r - show TPS information in tab list
  §a/<command> toggle disable§r - close TPS show

toggle:
  message:
    bar: "[Tpsx] §eswitch to the action bar mode§r"
    tab: "[Tpsx] §eswitch to the tab list mode§r"
    disable: "[Tpsx] §eturn off TPS display§r"
    from_server: "toggle is only available to players"

reload:
  message:
    success: "Config reload successfully"
